# Generated by Django 4.2.2 on 2023-08-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplistproduct',
            name='description',
            field=models.CharField(default='Описание товара', max_length=500),
        ),
    ]
