# Generated by Django 4.2.2 on 2023-08-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0002_shoplistproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplistproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
