# Generated by Django 4.2.2 on 2023-08-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='shoplistproduct',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='shoplistproduct',
            name='product_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
