# Generated by Django 4.2.2 on 2023-08-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0005_alter_category_options_alter_shoplistproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplistproduct',
            name='product_category',
        ),
        migrations.AddField(
            model_name='shoplistproduct',
            name='product_category',
            field=models.ManyToManyField(related_name='categories', to='shoplist.category'),
        ),
    ]
