# Generated by Django 4.2.2 on 2023-08-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0007_remove_shoplistproduct_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplistproduct',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('M', 'm'), ('L', 'l')], default='s', max_length=2),
        ),
        migrations.AlterField(
            model_name='shoplistproduct',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoplist.category'),
        ),
    ]
