# Generated by Django 4.2.2 on 2023-08-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0008_shoplistproduct_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_img', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='shoplistproduct',
            name='description',
            field=models.TextField(default='Описание товара'),
        ),
        migrations.AlterField(
            model_name='shoplistproduct',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='s', max_length=2),
        ),
        migrations.AddField(
            model_name='shoplistproduct',
            name='imgs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoplist.image'),
        ),
    ]
