# Generated by Django 4.2.2 on 2023-08-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0009_image_alter_shoplistproduct_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoplistproduct',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='shoplistproduct',
            name='upload',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoplist.shoplistproduct'),
        ),
    ]
