# Generated by Django 4.2.2 on 2023-08-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0010_gallery_remove_shoplistproduct_imgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplistproduct',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
