# Generated by Django 4.2.2 on 2023-08-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0011_shoplistproduct_title_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_color', models.CharField(max_length=30)),
                ('add_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='shoplist.shoplistproduct')),
            ],
        ),
    ]
