# Generated by Django 4.2.2 on 2023-08-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0012_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplistproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
