# Generated by Django 4.2.2 on 2023-09-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0013_shoplistproduct_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplistproduct',
            name='size',
        ),
        migrations.AlterField(
            model_name='color',
            name='add_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_color', to='shoplist.shoplistproduct'),
        ),
    ]
