# Generated by Django 4.2.2 on 2023-09-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0014_remove_shoplistproduct_size_alter_color_add_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_size', models.CharField(max_length=30)),
                ('add_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_size', to='shoplist.shoplistproduct')),
            ],
        ),
    ]
